name: build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run linter
        uses: DeLaGuardo/clojure-lint-action@v1
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.492'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13'

      - name: Install npm deps
        run: npm install

      - name: Run clean
        run: make clean

      - name: Run tests
        run: make test

      - name: Run build
        run: make build
