name: deploy

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch tags
        run: |
          git fetch --prune --unshallow

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          server-id: clojars
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: latest

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.05.09'

      - name: Cache m2 deps
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Cache node deps
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install npm deps
        run: npm install

      - name: Run tests
        run: make test

      - name: Run build
        run: make jar

      - name: Run deploy
        run: make deploy
